# EDA

In [2]:
# Importation des librairies
import pandas as pd
import numpy as np 
import seaborn

In [14]:
# Importation du dataset
df = pd.read_csv("C:\\Suppply Chain Project  - Looker Studio\\data\\raw\\DataCoSupplyChainDataset.csv", sep=",", encoding="latin-1")
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

<h3>Profilage des données<h3>

In [15]:
# Observation des 5 premières lignes
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [16]:
# Obervation des 5 dernières lignes
df.tail()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [17]:
# Information structurelles du dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [18]:
# Resumé statistique
df.describe(include='all')

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
count,180519,180519.000000,180519.000000,180519.000000,180519.000000,180519,180519.000000,180519.000000,180519,180519,...,24840.000000,180519.000000,180519.000000,0.0,180519,180519,180519.000000,180519.0,180519,180519
unique,4,NaN,NaN,NaN,NaN,4,NaN,NaN,50,563,...,NaN,NaN,NaN,NaN,118,118,NaN,NaN,63701,4
top,DEBIT,NaN,NaN,NaN,NaN,Late delivery,NaN,NaN,Cleats,Caguas,...,NaN,NaN,NaN,NaN,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,NaN,NaN,1/5/2016 5:58,Standard Class
freq,69295,NaN,NaN,NaN,NaN,98977,NaN,NaN,24551,66770,...,NaN,NaN,NaN,NaN,24515,24515,NaN,NaN,10,107752
mean,NaN,3.497654,2.931847,21.974989,183.107609,NaN,0.548291,31.851451,NaN,NaN,...,55426.132327,692.509764,31.851451,NaN,NaN,NaN,141.232550,0.0,NaN,NaN
std,NaN,1.623722,1.374449,104.433526,120.043670,NaN,0.497664,15.640064,NaN,NaN,...,31919.279101,336.446807,15.640064,NaN,NaN,NaN,139.732492,0.0,NaN,NaN
min,NaN,0.000000,0.000000,-4274.979980,7.490000,NaN,0.000000,2.000000,NaN,NaN,...,1040.000000,19.000000,2.000000,NaN,NaN,NaN,9.990000,0.0,NaN,NaN
25%,NaN,2.000000,2.000000,7.000000,104.379997,NaN,0.000000,18.000000,NaN,NaN,...,23464.000000,403.000000,18.000000,NaN,NaN,NaN,50.000000,0.0,NaN,NaN
50%,NaN,3.000000,4.000000,31.520000,163.990005,NaN,1.000000,29.000000,NaN,NaN,...,59405.000000,627.000000,29.000000,NaN,NaN,NaN,59.990002,0.0,NaN,NaN
75%,NaN,5.000000,4.000000,64.800003,247.399994,NaN,1.000000,45.000000,NaN,NaN,...,90008.000000,1004.000000,45.000000,NaN,NaN,NaN,199.990005,0.0,NaN,NaN
max,NaN,6.000000,4.000000,911.799988,1939.989990,NaN,1.000000,76.000000,NaN,NaN,...,99301.000000,1363.000000,76.000000,NaN,NaN,NaN,1999.989990,0.0,NaN,NaN

In [20]:
# Types de connes du dataset!
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [51]:
### Pourcentage des valeurs manquantes du dataset ###
nb_cells = df.shape[0]*df.shape[1]
print("Nombre de cellules : ", nb_cells)

Pct_nan = (df.isna().sum().sum() / nb_cells)*100
print("Pourcetage de valeurs manquantes : ", Pct_nan)

Nombre de cellules :  9567507
Pourcetage de valeurs manquantes :  3.5140711159134765

In [21]:
# Colonnes du dataset
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [34]:
# Observation des colonnes Customer Country et Order Country ?
df[["Customer Country", "Order Country"]].head(2)

  Customer Country Order Country
0      Puerto Rico     Indonesia
1      Puerto Rico         India

In [37]:
# Redondances - Sales vs Order 
print("\nSales vs Order Item Total:")
df[['Sales', 'Order Item Total']].head()

Sales vs Order Item Total:

    Sales  Order Item Total
0  327.75        314.640015
1  327.75        311.359985
2  327.75        309.720001
3  327.75        304.809998
4  327.75        298.250000

In [43]:
# Redondances - Sales per customer vs Sales 
print("\n Sales per customer vs Sales:")
df[['Sales per customer', 'Sales']].head(5)

 Sales per customer vs Sales:

   Sales per customer   Sales
0          314.640015  327.75
1          311.359985  327.75
2          309.720001  327.75
3          304.809998  327.75
4          298.250000  327.75

In [44]:
# Redondances - Product Price vs Order Item Product Price
print("\n Product Price vs Order Item Product Price:")
df[['Product Price', 'Order Item Product Price']].head(5)

 Product Price vs Order Item Product Price:

   Product Price  Order Item Product Price
0         327.75                    327.75
1         327.75                    327.75
2         327.75                    327.75
3         327.75                    327.75
4         327.75                    327.75

In [45]:
# Redondances - Order Item Profit Ratio vs Order Profit Per Order
print("\n Order Item Profit Ratio vs Order Profit Per Order:")
df[['Order Item Profit Ratio', 'Order Profit Per Order']].head(5)

 Order Item Profit Ratio vs Order Profit Per Order:

   Order Item Profit Ratio  Order Profit Per Order
0                     0.29               91.250000
1                    -0.80             -249.089996
2                    -0.80             -247.779999
3                     0.08               22.860001
4                     0.45              134.210007

In [ ]:
# Récap colonnes restantes à verifier
print(df['Order City'].nunique())
print(df['Order State'].nunique())
print(df['Product Name'].nunique())
print(df['Customer Id'].nunique())

3597
1089
118
20652

In [47]:
# Sélection des colonnes retenues
df_c = df[[
    # Délais & Livraison
    'Days for shipping (real)',
    'Days for shipment (scheduled)',
    'Delivery Status',
    'Late_delivery_risk',
    'Shipping Mode',
    'order date (DateOrders)',
    'shipping date (DateOrders)',
    # Géographie
    'Market',
    'Order Region',
    'Order Country',
    # Client
    'Customer Segment',
    # Commande & Produit
    'Order Status',
    'Category Name',
    'Product Name',
    'Order Item Quantity',
    # Finance
    'Sales',
    'Benefit per order',
    'Order Profit Per Order',
    'Order Item Profit Ratio'
]]

print(df_c.shape)

(180519, 19)

In [48]:
df_c.head(10)

,Days for shipping (real),Days for shipment (scheduled),Delivery Status,Late_delivery_risk,Shipping Mode,order date (DateOrders),shipping date (DateOrders),Market,Order Region,Order Country,Customer Segment,Order Status,Category Name,Product Name,Order Item Quantity,Sales,Benefit per order,Order Profit Per Order,Order Item Profit Ratio
0,3,4,Advance shipping,0,Standard Class,1/31/2018 22:56,2/3/2018 22:56,Pacific Asia,Southeast Asia,Indonesia,Consumer,COMPLETE,Sporting Goods,Smart watch,1,327.75,91.250000,91.250000,0.29
1,5,4,Late delivery,1,Standard Class,1/13/2018 12:27,1/18/2018 12:27,Pacific Asia,South Asia,India,Consumer,PENDING,Sporting Goods,Smart watch,1,327.75,-249.089996,-249.089996,-0.80
2,4,4,Shipping on time,0,Standard Class,1/13/2018 12:06,1/17/2018 12:06,Pacific Asia,South Asia,India,Consumer,CLOSED,Sporting Goods,Smart watch,1,327.75,-247.779999,-247.779999,-0.80
3,3,4,Advance shipping,0,Standard Class,1/13/2018 11:45,1/16/2018 11:45,Pacific Asia,Oceania,Australia,Home Office,COMPLETE,Sporting Goods,Smart watch,1,327.75,22.860001,22.860001,0.08
4,2,4,Advance shipping,0,Standard Class,1/13/2018 11:24,1/15/2018 11:24,Pacific Asia,Oceania,Australia,Corporate,PENDING_PAYMENT,Sporting Goods,Smart watch,1,327.75,134.210007,134.210007,0.45
5,6,4,Shipping canceled,0,Standard Class,1/13/2018 11:03,1/19/2018 11:03,Pacific Asia,Oceania,Australia,Consumer,CANCELED,Sporting Goods,Smart watch,1,327.75,18.580000,18.580000,0.06
6,2,1,Late delivery,1,First Class,1/13/2018 10:42,1/15/2018 10:42,Pacific Asia,Eastern Asia,China,Home Office,COMPLETE,Sporting Goods,Smart watch,1,327.75,95.180000,95.180000,0.33
7,2,1,Late delivery,1,First Class,1/13/2018 10:21,1/15/2018 10:21,Pacific Asia,Eastern Asia,China,Corporate,PROCESSING,Sporting Goods,Smart watch,1,327.75,68.430000,68.430000,0.24
8,3,2,Late delivery,1,Second Class,1/13/2018 10:00,1/16/2018 10:00,Pacific Asia,Eastern Asia,China,Corporate,CLOSED,Sporting Goods,Smart watch,1,327.75,133.720001,133.720001,0.48
9,2,1,Late delivery,1,First Class,1/13/2018 9:39,1/15/2018 9:39,Pacific Asia,Eastern Asia,China,Corporate,CLOSED,Sporting Goods,Smart watch,1,327.75,132.149994,132.149994,0.48

In [55]:
# Renomage des colonnes
df_c = df_c.rename(columns={
    'order date (DateOrders)'        : 'order_date',
    'shipping date (DateOrders)'     : 'dispatch_date',
    'Days for shipping (real)'       : 'delivery_days_real',
    'Days for shipment (scheduled)'  : 'delivery_days_scheduled',
    'Delivery Status'                : 'delivery_status',
    'Late_delivery_risk'             : 'late_delivery_risk',
    'Shipping Mode'                  : 'shipping_mode',
    'Market'                         : 'market',
    'Order Region'                   : 'order_region',
    'Order Country'                  : 'order_country',
    'Customer Segment'               : 'customer_segment',
    'Order Status'                   : 'order_status',
    'Category Name'                  : 'category_name',
    'Product Name'                   : 'product_name',
    'Order Item Quantity'             : 'quantity',
    'Sales'                          : 'sales',
    'Benefit per order'              : 'benefit_per_order',
    'Order Profit Per Order'         : 'profit_per_order',
    'Order Item Profit Ratio'        : 'profit_ratio'
})

print(df_c.columns.tolist())

['delivery_days_real', 'delivery_days_scheduled', 'delivery_status', 'late_delivery_risk', 'shipping_mode', 'order_date', 'dispatch_date', 'market', 'order_region', 'order_country', 'customer_segment', 'order_status', 'category_name', 'product_name', 'quantity', 'sales', 'benefit_per_order', 'profit_per_order', 'profit_ratio']

In [56]:
### Pourcentage des valeurs manquantes du dataset ###
nb_cells = df_c.shape[0]*df_c.shape[1]
print("Nombre de cellules : ", nb_cells)

Pct_nan = (df_c.isna().sum().sum() / nb_cells)*100
print("Pourcetage de valeurs manquantes : ", Pct_nan)

Nombre de cellules :  3429861
Pourcetage de valeurs manquantes :  0.0

In [57]:
# revérification des types
df_c.dtypes

delivery_days_real           int64
delivery_days_scheduled      int64
delivery_status             object
late_delivery_risk           int64
shipping_mode               object
order_date                  object
dispatch_date               object
market                      object
order_region                object
order_country               object
customer_segment            object
order_status                object
category_name               object
product_name                object
quantity                     int64
sales                      float64
benefit_per_order          float64
profit_per_order           float64
profit_ratio               float64
dtype: object

<h4>Traitement des dates<h4>

In [60]:
# Conversion des dates en datetime
df_c['order_date']    = pd.to_datetime(df_c['order_date'])
df_c['dispatch_date'] = pd.to_datetime(df_c['dispatch_date'])

In [61]:
# Calcul des dates de livraison
df_c['delivery_date_real']      = df_c['dispatch_date'] + pd.to_timedelta(df_c['delivery_days_real'], unit='d')
df_c['delivery_date_scheduled'] = df_c['dispatch_date'] + pd.to_timedelta(df_c['delivery_days_scheduled'], unit='d')

In [62]:
# Vérification
df_c[['dispatch_date', 'delivery_days_real', 'delivery_date_real', 'delivery_date_scheduled']].head(5)

,dispatch_date,delivery_days_real,delivery_date_real,delivery_date_scheduled
0,2018-02-03 22:56:00,3,2018-02-06 22:56:00,2018-02-07 22:56:00
1,2018-01-18 12:27:00,5,2018-01-23 12:27:00,2018-01-22 12:27:00
2,2018-01-17 12:06:00,4,2018-01-21 12:06:00,2018-01-21 12:06:00
3,2018-01-16 11:45:00,3,2018-01-19 11:45:00,2018-01-20 11:45:00
4,2018-01-15 11:24:00,2,2018-01-17 11:24:00,2018-01-19 11:24:00

<h4>Traitement des dates fin.<h4>

In [64]:
# Vérification des Doublons
print("Doublons :", df_c.duplicated().sum())

Doublons : 5

In [71]:
# Suppression des doublons
df_c = df_c.drop_duplicates()

# Vérification
print("Doublons :", df_c.duplicated().sum())
print("Shape après suppression :", df_c.shape)

Doublons : 0
Shape après suppression : (180514, 21)

In [72]:
# Valeurs aberrantes sur les délais
print("Delai réel - stats:")
print(df_c['delivery_days_real'].describe())

Delai réel - stats:
count    180514.000000
mean          3.497695
std           1.623715
min           0.000000
25%           2.000000
50%           3.000000
75%           5.000000
max           6.000000
Name: delivery_days_real, dtype: float64

In [73]:
print("\nDelai prévu - stats:")
print(df_c['delivery_days_scheduled'].describe())

Delai prévu - stats:
count    180514.000000
mean          2.931883
std           1.374432
min           0.000000
25%           2.000000
50%           4.000000
75%           4.000000
max           4.000000
Name: delivery_days_scheduled, dtype: float64

In [74]:
# Cohérence des dates
print("\nDates incohérentes (livraison avant expédition):")
print((df_c['delivery_date_real'] < df_c['dispatch_date']).sum())

Dates incohérentes (livraison avant expédition):
0